ALTER TABLE "WorkoutItem" ADD COLUMN IF NOT EXISTS "load" TEXT;
ALTER TABLE "WorkoutItem" ADD COLUMN IF NOT EXISTS "rpe" TEXT;
ALTER TABLE "WorkoutTemplateItem" ADD COLUMN IF NOT EXISTS "load" TEXT;
ALTER TABLE "WorkoutTemplateItem" ADD COLUMN IF NOT EXISTS "rpe" TEXT;
